type apimSubscription = {
  id: string
  displayName: string
  productId: 'bronze' | 'silver' | 'gold'
  lineOfBusiness: string
  useCase: string
  enabled: bool
}

@description('Name of the existing APIM service that owns the subscriptions.')
param apimName string

@description('Azure region for the reconciliation identity and deployment script.')
param location string

@description('Catalog of APIM subscriptions. Keys are generated by APIM and are never stored in the catalog.')
param subscriptionCatalog apimSubscription[]

@description('Forces the idempotent reconciliation script to run during each provision.')
param forceUpdateTag string

param tags object = {}

var desiredSubscriptions = filter(subscriptionCatalog, subscription => subscription.enabled)
// Retain retired catalog IDs until every environment has reconciled their deletion.
var retiredSubscriptionIds = [
  'test-bronze'
  'test-silver'
  'test-silver-2'
  'test-gold'
]
var managedSubscriptionIds = union(map(subscriptionCatalog, subscription => subscription.id), retiredSubscriptionIds)
var desiredSubscriptionIds = map(desiredSubscriptions, subscription => subscription.id)
var apiManagementServiceContributorRoleId = '312a565d-c81f-4fd8-895a-4e21e48d571c'

resource apim 'Microsoft.ApiManagement/service@2023-05-01-preview' existing = {
  name: apimName
}

@batchSize(1)
resource apimUsers 'Microsoft.ApiManagement/service/users@2023-05-01-preview' = [for subscription in desiredSubscriptions: {
  parent: apim
  name: subscription.id
  properties: {
    email: '${subscription.id}@subscriptions.example.com'
    firstName: 'APIM'
    lastName: subscription.id
    note: 'Non-human owner for the ${subscription.id} APIM subscription.'
    state: 'active'
  }
}]

@batchSize(1)
resource apimSubscriptions 'Microsoft.ApiManagement/service/subscriptions@2023-05-01-preview' = [for subscription in desiredSubscriptions: {
  parent: apim
  name: subscription.id
  properties: {
    displayName: subscription.displayName
    ownerId: resourceId('Microsoft.ApiManagement/service/users', apimName, subscription.id)
    scope: resourceId('Microsoft.ApiManagement/service/products', apimName, subscription.productId)
    state: 'active'
  }
  dependsOn: [
    apimUsers
  ]
}]

resource reconciliationIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-${take(apimName, 42)}-subscription-reconciler'
  location: location
  tags: tags
}

resource reconciliationRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: apim
  name: guid(apim.id, reconciliationIdentity.id, apiManagementServiceContributorRoleId)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', apiManagementServiceContributorRoleId)
    principalId: reconciliationIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource subscriptionReconciliation 'Microsoft.Resources/deploymentScripts@2023-08-01' = {
  name: 'ds-${take(apimName, 43)}-subscriptions'
  location: location
  kind: 'AzureCLI'
  tags: union(tags, { SecurityControl: 'Ignore' })
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${reconciliationIdentity.id}': {}
    }
  }
  properties: {
    azCliVersion: '2.87.0'
    cleanupPreference: 'OnSuccess'
    retentionInterval: 'PT1H'
    timeout: 'PT15M'
    forceUpdateTag: forceUpdateTag
    environmentVariables: [
      {
        name: 'APIM_RESOURCE_ID'
        value: apim.id
      }
      {
        name: 'MANAGED_SUBSCRIPTION_IDS'
        value: join(managedSubscriptionIds, ',')
      }
      {
        name: 'DESIRED_SUBSCRIPTION_IDS'
        value: join(desiredSubscriptionIds, ',')
      }
    ]
    scriptContent: '''
      #!/bin/bash
      set -euo pipefail

      existing_ids=""
      for attempt in $(seq 1 20); do
        if existing_ids=$(az rest \
          --method GET \
          --uri "${APIM_RESOURCE_ID}/subscriptions?api-version=2023-05-01-preview" \
          --query 'value[].name' \
          --output tsv 2>/tmp/apim-subscription-error.log); then
          break
        fi

        if [ "$attempt" -eq 20 ]; then
          cat /tmp/apim-subscription-error.log >&2
          exit 1
        fi
        sleep 15
      done

      IFS=',' read -ra managed_ids <<< "$MANAGED_SUBSCRIPTION_IDS"
      for subscription_id in "${managed_ids[@]}"; do
        [ -z "$subscription_id" ] && continue
        if [[ ",$DESIRED_SUBSCRIPTION_IDS," == *",$subscription_id,"* ]]; then
          continue
        fi
        if ! grep -Fxq "$subscription_id" <<< "$existing_ids"; then
          continue
        fi

        az rest \
          --method DELETE \
          --uri "${APIM_RESOURCE_ID}/subscriptions/${subscription_id}?api-version=2023-05-01-preview" \
          --output none
      done

      printf '{}\n' > "$AZ_SCRIPTS_OUTPUT_PATH"
    '''
  }
  dependsOn: [
    reconciliationRole
    apimSubscriptions
  ]
}

output configuredSubscriptionIds array = desiredSubscriptionIds
